import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { NotchNav } from "@/components/ui/notch-nav";
import { ThemeToggle } from "@/components/ui/theme-toggle";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

type NavIcon = "home" | "dashboard" | "history"

const navItems: Array<{
  value: string
  label: string
  href: string
  icon: NavIcon
}> = [
  { value: "home", label: "Home", href: "/", icon: "home" },
  { value: "dashboard", label: "Dashboard", href: "/dashboard", icon: "dashboard" },
  { value: "history", label: "History", href: "/history", icon: "history" },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col bg-background text-foreground">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="border-b border-border bg-card/90 backdrop-blur">
            <div className="mx-auto flex w-full max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6">
              <NotchNav items={navItems} defaultValue="home" ariaLabel="Primary navigation" />
              <ThemeToggle />
            </div>
          </header>
          <main className="flex-1">{children}<Toaster />
</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
